services:
  accounts:
    image: miladsade96/accounts:s4
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 1024m
    networks:
      - default

  loans:
    image: miladsade96/loans:s4
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 1024m
    networks:
      - default

  cards:
    image: miladsade96/cards:s4
    container_name: cards-ms
    ports:
      - "8070:8070"
    deploy:
      resources:
        limits:
          memory: 1024m
    networks:
      - default

networks:
  default:
    driver: bridge
