spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0.0"

accounts:
  message: "Welcome to the Accounts Service - QA Environment"
  contactDetails:
    name: "John Doe"
    email: "JohnDoe@gmail.com"
  onCallSupport:
    - 123-456-7890
    - 987-654-3210
